In [45]:
import numpy as np

In [46]:
np.zeros(7,dtype=int)

array([0, 0, 0, 0, 0, 0, 0])

In [47]:
u = np.arange(1,77800,4)
u

array([ 1, 5, 9, ..., 77789, 77793, 77797])

To jest analiza bilbioteki **numpy**
<h3>Bilioteka NUMPY</h3>
<p style="color:red;">biblioteka numeryczna służąca do organizacji n-wymiarowych źródeł danych</p>
<img src="spaceship.jpg" width=500>

In [48]:
lzw = [4,7,2,89,3,56,7,25,89,4]
lzw

[4, 7, 2, 89, 3, 56, 7, 25, 89, 4]

In [49]:
print(type(lzw))
print(type(u))

<class 'list'>
<class 'numpy.ndarray'>


In [50]:
mlista = np.array(lzw)
wlista = np.array(u)
full = np.concatenate((u,lzw))
full

array([ 1, 5, 9, ..., 25, 89, 4])

In [51]:
mcx = np.array([[13,7],[99,5]])
mcx

array([[13, 7],
 [99, 5]])

In [52]:
mcy = np.array([[104,108],[23,56]])
mcy

array([[104, 108],
 [ 23, 56]])

In [53]:
wmc = np.concatenate((mcx,mcy),axis=0)
wmc

array([[ 13, 7],
 [ 99, 5],
 [104, 108],
 [ 23, 56]])

In [54]:
pr = np.arange(12)
pr

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

In [55]:
rs = pr.reshape(6,2)
rs

array([[ 0, 1],
 [ 2, 3],
 [ 4, 5],
 [ 6, 7],
 [ 8, 9],
 [10, 11]])

In [56]:
mmc = np.array([[34,7,8,13],[4,5,6,7],[99,88,77,1]])
mmc

array([[34, 7, 8, 13],
 [ 4, 5, 6, 7],
 [99, 88, 77, 1]])

In [57]:
print(mmc[mmc<10])

[7 8 4 5 6 7 1]


In [58]:
war = (mmc>=18)
print(mmc[war])

[34 99 88 77]


In [59]:
w2 = (mmc%2==0)
mmc[w2]

array([34, 8, 4, 6, 88])

In [60]:
c = mmc[(mmc>7)&(mmc<27)]
c

array([ 8, 13])

In [61]:
d = mmc[(mmc<8)|(mmc>43)]
d

array([ 7, 4, 5, 6, 7, 99, 88, 77, 1])

In [62]:
#tensor
arr3d = np.array([[[2,5,8],[3,9,11]],[[16,18,22],[99,12,66]]])
arr3d

array([[[ 2,  5,  8],
        [ 3,  9, 11]],

       [[16, 18, 22],
        [99, 12, 66]]])

In [63]:
arr3d[0]

array([[ 2, 5, 8],
 [ 3, 9, 11]])

In [64]:
old_v = arr3d[0].copy()
arr3d[0] = 88
arr3d

array([[[88, 88, 88],
        [88, 88, 88]],

       [[16, 18, 22],
        [99, 12, 66]]])

In [65]:
arr3d[0] = old_v
arr3d

array([[[ 2,  5,  8],
        [ 3,  9, 11]],

       [[16, 18, 22],
        [99, 12, 66]]])

In [67]:
arr3d[1,1,0]

99

In [68]:
arr3d.shape

(2, 2, 3)